import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "tnjensen's portfolio",
  description: "Generated by tnjensen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
          <div className="mx-auto min-h-[calc(100vh-80px)] bg-main-bg w-full max-w-7xl">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
