name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 1. Naviger til tnjensen.com mappen eller klon den hvis den er tom
            if [ ! -d "/var/www/tnjensen.com" ] || [ -z "$(ls -A /var/www/tnjensen.com)" ]; then
              sudo mkdir -p /var/www/tnjensen.com
              sudo chown -R $USER:$USER /var/www/tnjensen.com
              git clone https://github.com{{ github.repository }}.git /var/www/tnjensen.com
              cd /var/www/tnjensen.com
            else
              cd /var/www/tnjensen.com
              git pull origin main
            fi

            # 2. Installer avhengigheter og bygg standalone-versjonen
            npm install
            npm run build

            # 3. Kopier statiske filer inn i standalone-mappen
            cp -r .next/static .next/standalone/.next/
            cp -r public .next/standalone/

            # 4. Start eller start på nytt i PM2
            pm2 describe nextjs-standalone > /dev/null
            if [ $? -eq 0 ]; then
              PORT=3000 pm2 restart nextjs-standalone --update-env
            else
              PORT=3000 pm2 start .next/standalone/server.js --name "nextjs-standalone"
            fi
            pm2 save
